### ISSUE TITLE
Compiling in Window 7

### ISSUE THREAD

**Issue by boonpingng** [dhoegh/BuildExecutable.jl#29]
Hi,

I am using Julia to compile a simple code.

function main()
    println("It works")
end

Seems like it does not work. 

There are two errors:

ERROR: LoadError: failed process: Process(`'C:\Users\bpng\.julia\v0.4\WinRPM\dep
s\usr\x86_64-w64-mingw32\sys-root\mingw\bin\gcc.exe' '-LC:\Users\bpng\Julia-0.4.
6\bin' -shared -ljulia -lssp -o 'C:\Users\bpng\Julia-0.4.6\bin\libtryexe.exe.dll
' 'C:\Users\bpng\Julia-0.4.6\bin\libtryexe.exe.o'`, ProcessExited(1)) [1]
 in run at process.jl:531
while loading C:\Users\bpng\.julia\v0.4\BuildExecutable\src\build_sysimg.jl, in
expression starting on line 187
ERROR: failed process: Process(`'C:\Users\bpng\Julia-0.4.6\bin\julia' 'C:\Users\
bpng\.julia\v0.4\BuildExecutable\src\build_sysimg.jl' 'C:\Users\bpng\Julia-0.4.6
\bin\libtryexe.exe' native 'C:\Users\bpng\AppData\Local\Temp\julE00F.tmp\userimg
.jl' --force`, ProcessExited(1)) [1]
 in run at process.jl:531

May I know how can I solve them?

Thanks.

**Comment by dhoegh** [comment]
Hi i think your issue is caused by what i describe in https://github.com/dhoegh/BuildExecutable.jl/issues/28#issuecomment-270179437.
