### ISSUE TITLE
ERROR: LoadError: Unable to modfy /usr/lib/...

### ISSUE THREAD

**Issue by gideonite** [dhoegh/BuildExecutable.jl#5]
Hi,

I've been having a lot of trouble trying to compile a julia program to a standalone binary. I want to do this in order to run a program on a cluster that does not have Julia installed. Perhaps you have some advice.

I keep getting an error:

```
ERROR: LoadError: failed process: Process(`/usr/bin/julia -C native --output-ji /usr/lib/julia/lib..ji --output-o /usr/lib/julia/lib..o -J /usr/lib/julia/inference.ji --startup-file=no sysimg.jl`, ProcessExited(1)) [1]
 in anonymous at /usr/share/julia/build_sysimg.jl:66
 in build_sysimg at /usr/share/julia/build_sysimg.jl:27
while loading /usr/share/julia/build_sysimg.jl, in expression starting on line 175
ERROR: LoadError: failed process: Process(`/usr/bin/julia /usr/share/julia/build_sysimg.jl /usr/lib/julia/lib. native /tmp/tmpdemsq8/userimg.jl --force`, ProcessExited(1)) [1]
 in build_executable at /usr/share/julia/build_executable.jl:109
 in build_executable at /usr/share/julia/build_executable.jl:58
while loading /usr/share/julia/build_executable.jl, in expression starting on line 277
```

This is my program:

```
function main()
    println("HELLO WORLD")
end
```

And the command I'm running is

```
julia /usr/share/julia/build_executable.jl helloworld /home/gideon/hello_world/hello_world.jl --force
```

Thanks!

**Comment by dhoegh** [comment]
Could your try to do the following and post the output?

```
Pkg.clone("https://github.com/dhoegh/BuildExecutable.jl")
Pkg.test("BuildExecutable")
```

As i have changed a couple of things in the script in this repository. What are your `versioninfo()`. If you are on OSX you need to checkout #2. I still need to clean it up, but it works on Travis OSX.

**Comment by gideonite** [comment]
Indeed you were right. Running the tests gave some errors:

```
INFO: Testing BuildExecutable
running: /usr/bin/julia /usr/share/julia/build_sysimg.jl /usr/lib/julia/libtest_executable native /tmp/tmpTylHkc/userimg.jl --force
ERROR: LoadError: Unable to modify /usr/lib/julia/libtest_executable.ji, ensure parent directory exists and is writable. Absolute paths work best.)
 in anonymous at /usr/share/julia/build_sysimg.jl:37
 in build_sysimg at /usr/share/julia/build_sysimg.jl:27
while loading /usr/share/julia/build_sysimg.jl, in expression starting on line 175
ERROR: LoadError: test error in expression: build_executable(exename,script,targetdir,"native"; force=false) == 0
failed process: Process(`/usr/bin/julia /usr/share/julia/build_sysimg.jl /usr/lib/julia/libtest_executable native /tmp/tmpTylHkc/userimg.jl --force`, ProcessExited(1)) [1]
 in build_executable at /home/gideon/.julia/v0.4/BuildExecutable/src/BuildExecutable.jl:111
 in anonymous at test.jl:90
 in do_test at test.jl:50
 [inlined code] from /home/gideon/.julia/v0.4/BuildExecutable/test/runtests.jl:9
 in anonymous at no file:0
 in build_executable at /home/gideon/.julia/v0.4/BuildExecutable/src/BuildExecutable.jl:111
 in anonymous at test.jl:90
 in do_test at test.jl:50
 [inlined code] from /home/gideon/.julia/v0.4/BuildExecutable/test/runtests.jl:9
 in anonymous at no file:0
while loading /home/gideon/.julia/v0.4/BuildExecutable/test/runtests.jl, in expression starting on line 8
=============================================================================================[ ERROR: BuildExecutable ]=============================================================================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/gideon/.julia/v0.4/BuildExecutable/test/runtests.jl`, ProcessExited(1)) [1]

====================================================================================================================================================================================================================
ERROR: BuildExecutable had test errors
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

`versioninfo()` is 

```
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.3
```

I'm running arch linux.

**Comment by dhoegh** [comment]
A comment on a line just before the error is thrown, states that you need write permission to `/usr/lib/julia/` could you try to start julia in `sudo` and do `Pkg.test("BuildExecutable")`

**Comment by dhoegh** [comment]
BTW if when you get the test working and afterwards do `build_executable(exename, script, targetdir, "native"; force=false)` you should be aware that the machine you transfer the executable to understand the same CPU instructions. You can change the executable to use an older instruction set by doing `build_executable(exename, script, targetdir, "core2"; force=false)`

**Comment by gideonite** [comment]
Just tried running julia in sudo. Got another error...

```
julia> Pkg.test("BuildExecutable")
INFO: Initializing package repository /root/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: BuildExecutable did not provide a test/runtests.jl file
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

I was originally using `contrib/build_executable.jl` and running it in
sudo, but with similar error messages.

Ahh, thanks for the comment about `"core2"`. I was wondering about that.
Still not sure what `"core2"` refers to though.

**Comment by dhoegh** [comment]
It seems like you do not have access to the previous clone of this package. Could you try to start julia in sudo and do

```
Pkg.clone("https://github.com/dhoegh/BuildExecutable.jl")
Pkg.test("BuildExecutable")
```

> Ahh, thanks for the comment about `"core2"`. I was wondering about that.
> Still not sure what `"core2"` refers to though.

I am not completely sure either. It has something to do with which instructions the CPU understands in the machine code.

**Comment by gideonite** [comment]
Nice, tests passed and now it works for my "hello world" example!

But,
(1) it doesn't work as soon as I start `using DataFrames`

```
error during bootstrap:
LoadError(at "sysimg.jl" line 319: LoadError(at
"/usr/share/julia/base/userimg.jl" line 1: LoadError(at
"/home/gideon/hello_world/hello_world.jl" line 1:
Base.ArgumentError(msg="DataFrames not found in path"))))
```

(2) the hello world binary doesn't run on my cluster because it can't find
`libjulia.so`. I was afraid of this. Does it mean that compiling a simple
binary executable that can be "run anywhere" is beyond reach?

**Comment by dhoegh** [comment]
I should have fixed the realacation issue for your "hello world" on the server see 6a1e0fd.

**Comment by gideonite** [comment]
Now I'm getting a different error.

```
ERROR: ArgumentError: '/home/gideon/hello_world/helloworld/helloworld'
exists. `remove_destination=true` is required to remove
'/home/gideon/hello_world/helloworld/helloworld' before moving.
 in checkfor_mv_cp_cptree at file.jl:90
 in build_executable at
/root/.julia/v0.4/BuildExecutable/src/BuildExecutable.jl:142
```

But `remove_destination` is not an argument to `build_executable`.

**Comment by dhoegh** [comment]
You need to remove the files in the folder `targetdir` as it tries to copyfiles to the directory that already exist. BTW the following is working fine for me

```
import DataFrames
import Base.Test
function main()
    df = DataFrames.@data([3, 2, 5, 4]) #Full qualification of names is required
    Base.Test.@test  maximum(df) == 5
    println("It works")
end
```

Full qualification of names in modules is required see: https://github.com/dhoegh/BuildExecutable.jl#note-on-packages

**Comment by dhoegh** [comment]
The error message should be better or not occur with c9d559b commit.

**Comment by gideonite** [comment]
Hooray! Yes, it compiled. Slowly I am learning =)

I copied over everything in `targetdir` to the server (a cluster) and tried
to run the helloworld program. Unfortunately, it seems the .so files in the
"package" are still missing one. Have you gotten the binary to run on other
computers?

```
./helloworld: error while loading shared libraries: libunwind.so.8: cannot
open shared object file: No such file or directory
```

**Comment by dhoegh** [comment]
I have used it to distribute a small program on different windows computers, but not on Linux. I do not have to much time to look into this. You could try to locate and copy `libunwind.so.8` to the `targetdir` and see if this helps.

**Comment by gideonite** [comment]
Ok. No problem.

Yeah, I tried but to no avail. It throws a bunch of other errors when I do
that. There isn't any sort of window versus linux setting somewhere is
there? My first thought was that `libunwind.so` is related to windows.

Thanks for the help. Maybe someday this will become a stable feature of
Julia.

**Comment by dhoegh** [comment]
libunwind is a library for call stack unwinding and is not windows specific.

> Thanks for the help. Maybe someday this will become a stable feature of
> Julia.

This solution is only a short term hack the Julia team plan to be able to statically compile julia see, https://github.com/JuliaLang/julia/pull/13677.

**Comment by gideonite** [comment]
I did a pull on the latest code and tried julia --compile=all but it's not
clear to me (or clearly documented it seems) what it does.
